pipeline:

  install requirements and test:
    image: python:3.7.2-stretch
    environment:
      FLASK_ENV: testing
      FLASK_TESTING: "True"
    commands:
    - cd src
    - pip install -r requirements.txt
    - python -m pytest

  publish:
    image: plugins/docker
    repo: iahmad/k8s-image-processor
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: k8s-image-processor
    username: drone
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded. Good job.
        Link ->  {{ build.link }}
      {{else}}
        Build {{build.number}} failed. Fix me please.
        Link -> {{ build.link }}
      {{/success}}
    